{% set name = "sqlalchemy-bigquery" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-bigquery-{{ version }}.tar.gz
  sha256: ca92a6de7ba3600235d29b20883a4ef3e964241b547e136d43cb6c0702edcbe8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0.0dev
    - google-cloud-bigquery-core >=2.25.2,<4.0.0dev
    - google-cloud-bigquery-storage >=2.0.0,<3.0.0dev
    - packaging
    - pyarrow >=3.0.0
    - sqlalchemy >=1.2.0,<2.0.0dev
    - future

test:
  imports:
    - sqlalchemy_bigquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-sqlalchemy
  summary: SQLAlchemy dialect for BigQuery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
