{% set name = "sqlalchemy-bigquery" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 12783ad83ffad34e8e6e14046cb14bb2f1a3e7fb52676f5a24e940ff5cdeb864

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - pip
    - setuptools
  run:
    - python >=3.8,<3.13
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0.0dev
    - google-cloud-bigquery-core >=3.3.6,<4.0.0dev
    - packaging
    - sqlalchemy >=1.4.16,<3.0.0dev

test:
  imports:
    - sqlalchemy_bigquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-sqlalchemy
  summary: SQLAlchemy dialect for BigQuery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
