{% set name = "sqlalchemy-bigquery" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-bigquery-{{ version }}.tar.gz
  sha256: f7537fa283687c31b6f8bf9d3c76d6a1fd5d1a1df8e814116a991b2339656c1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - pip
  run:
    - python >=3.8,<3.13
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0.0dev
    - google-cloud-bigquery-core >=2.25.2,<4.0.0dev
    - packaging
    - sqlalchemy >=1.2.0,<2.0.0dev

test:
  imports:
    - sqlalchemy_bigquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-sqlalchemy
  summary: SQLAlchemy dialect for BigQuery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
